version: "3.8"
services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb,lambda,sqs,apigateway
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
      - LAMBDA_EXECUTOR=docker-reuse
    volumes:
      - ../lambda:/lambda
      - ../lambda/setup.sh:/etc/localstack/init/ready.d/setup.sh:ro
      - /var/run/docker.sock:/var/run/docker.sock
